version: '3.8'

services:
  nats1:
    image: nats:2.10
    container_name: nats1
    ports:
      - "4222:4222"       # Client port
      - "8222:8222"       # Monitoring port
      - "6222:6222"       # Cluster port
    command: >
      -js
      -cluster nats://nats1:6222
      -routes nats://nats2:6222,nats://nats3:6222
    networks:
      - nats-network

  nats2:
    image: nats:2.10
    container_name: nats2
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6223:6222"
    command: >
      -js
      -cluster nats://nats2:6222
      -routes nats://nats1:6222,nats://nats3:6222
    networks:
      - nats-network

  nats3:
    image: nats:2.10
    container_name: nats3
    ports:
      - "4224:4222"
      - "8224:8222"
      - "6224:6222"
    command: >
      -js
      -cluster nats://nats3:6222
      -routes nats://nats1:6222,nats://nats2:6222
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge