version: '3.8'

services:
  nats1:
    image: nats:2.10
    container_name: nats1
    ports:
      - "4222:4222"       # Client port
      - "8222:8222"       # Monitoring port
      - "6222:6222"       # Cluster port
    environment:
      - NATS_SERVER_NAME=nats1
    command: ["-c", "/etc/nats/nats.conf", "--name", "nats1"]
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    networks:
      - nats-network
  nats2:
    image: nats:2.10
    container_name: nats2
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6223:6222"
    environment:
      - NATS_SERVER_NAME=nats2
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf", "--name", "nats2"]
    networks:
      - nats-network

  nats3:
    image: nats:2.10
    container_name: nats3
    ports:
      - "4224:4222"
      - "8224:8222"
      - "6224:6222"
    environment:
      - NATS_SERVER_NAME=nats3
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf", "--name", "nats3"]
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge